#!/usr/bin/env python3
# -*- coding: utf-8 -*-


from ete3 import EvolTree


tree = EvolTree("((expansion_LINE_CR1_rnd-1_family-1019_123,expansion_LINE_CR1_rnd-1_family-1019_144),rest_LINE_CR1_rnd-1_family-131_105);")

tree.link_to_alignment ('''>expansion_LINE_CR1_rnd-1_family-1019_123
TACCTTGACTTTGAAAAAGCATTTGACAAAGTCCCACACGACTATCTTCTTTTGAAACTAAAAGCCTATGGGATTAATGGTCCAATTCTCTCTTGGATAAGAAACTTTCTCACAAATCGAAGACAAAGAGTAATGATAAATGGTAATTACTCTGATTGGGTATCAGTAAAAAGTGGAGTTCCCCAAGGTTCTGTTCTCTCAGCTCTATTATTCATTATATACGTTAGCGATATTCCCAATATAATTACTTCAAATGCAGCACTTTTTGCTGACGATACAAAAATATTTTACCCTATTACTAATTTGCATTTACACACCGTACTTCAAAATGATATTGATATCTTGGTTGACTGGGCAACTAAATGGGGGATGAAATTTAATATAGAAAAATGTTCAGTTTTACACCTAGGTCATAAAAATAAACATCTTGTCTATTCTATGTACGATCCAGTGAAGAAAACAAGGATTGATATCAAATCTACCAACTCAGAAACTGACCTCGGAGTACAAATCGATAATAACTTGCTA---TTTTCTAAACATACCTCTACTCAAGTTAATAGGGCAATGCAGATGCTATTTCTAATAAAAAGATCTTTCTCTTATCTAAATTCATTTTGTTTTAAAAGACTGTTTTCAGCACTAGTACGACCATATTTAGAATATTGTGGTTCTGTATATAACCCTCGTCTACTGAAAGACAAACGACAAGTTGAAAATATACTCAGAAGAGCATCTAAATCAGTTCATGGATTAAAAAGTCTAACATATCACCAAAGACTATTG---AAACTTAATATGACAACCATAAGATACAGACTAATCCGGACTGATTTAATAAACGTCTATAAATGGCTAAACAACTACTACAACTGT------------CAAACGATCTTTCCA---AAAACAATTATAAATTCTATTACAAGAGGACATTCA---------------TTTAAACTA---------GAAAAACCT---TATTCTCATCTAGCTTCTCGTCAATACTTTTTCACCTTACGAGTAATCAACAAATGGAACTCCCTCCCAGATGACGTTGTAAAT------------GCTAATTTTTAA------------------------------------------------
>expansion_LINE_CR1_rnd-1_family-1019_144
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ATTACTAATTTGCATTCACACACCGTACTTCAAAATGATATTGATATTTTGGTTGACTGGGCAACTAAATGGGGGATGAAATTTAATACAGAAAAATGTTCAGTTTTACACCTAGATCATAAAAATAAACATCTTGTCTATTCTATGTACGATCCAGTGAAGAAAACAAGGATTGATATCAAATCTACCAACTCAGAAACTGACCTCGGAGTACATATCGATAATAACTTGCTA---TTTTCTAAACATACCTCTACTCAAGTTAATAGGGCAATGCAGATGCTATTTCTAATAAAAAGATCTTTCTCTTATCTAAATTCATTTTGTTTTAAAAGACTATTTTCAGCACTAGTACGACCATATTTAGAATATTGTGGTTCTGTATATAACCCTCGTCTACTGAAAGACAAACGACAAGTTGAAAATATACTCAGAAGAGCATCTAAATCAGTTCATGGATTAAAAAGTCTAACATATCACCAAAGACTATTG---AAACTTAATATGACAACCATAAGATACAGACTAATCCGGGCTGATTTAATAAACGTCTATAAATGGCTAAACAACTACTACAACTGT------------CAAACGATCTTTCCA---AAAACAATTATAAATTCTATTACAAGAGGACATTCA---------------TTTAAACTA---------GAAAAACCT---TATTCTCGTCTAGCTTCTCGTAAATATTTTTTCACCTTACGAGTAATCAACAAATGGAACTCCCTCCCAGATGACGTTGTAAATGCTACTTCCGTAAGCAATTTTAAAAACAAACTCGACAATTATCTAAAAGAAGAAAAAACAATTTATGACTAG
>rest_LINE_CR1_rnd-1_family-131_105
------------------------------------------------------------------ATGGGATACAACAAC---------------------------------------------------------------------------------------------------------------------------------------ATTCAT------------CCTAGAGTGCTCAAAGACTGTGCAAAAAGTTTTGCG------------------ATTTCATTAACAATTATCTATCCTCCTTCACTCAAAAGTGGTGAAATTCCTCATATG------------------TGGAAAATG------------------GTAAATATTTTTCCAATTTTTAAAAAAGGCAATAAATTAGAAGCTTCAAATTACAGAGGAGTTTCGTTAACATTTATTTTAAGTAAAATTATAGAAAGTGAAGCAATTATGAAACACTGTAGGGAAAACAATATTATCTCAATATCTCAACACGGT---------------------------------TTCATCTTAAAAAAAGAA---------------------TGTTTTACCAATTTACTTGAAACTTTG---------------------------GACATTGTTACA---AAAGCCATACAAAGTAATTATCGAGTTGACATAGTGTACACTGACTTGGAGAAAGCGTTTGATAAAGTGCCC------------CATCCCCGACTCATTCATAAAATAAGAGCATATGGCATACTAAGTCAATTGATTGCA------TTGATCGAAGCA------TGGCTCAAAAACAGAAAACAAAGAGTAGTATTGGGTGATTCTATATTTGAATGGAAAGACGTTACTAGCGGTGTACCTCAGGGTTCTGTACTAGGCCCTCTTTTGTTTGTTCTCTATGTCAATGATTTACCTAACCATATACATCATTCTATAAAACTCTACGCTGACAATATTAAGATAATCGGAGTTATTAAGACG---CCAGAAGAT---------------------GCTAATCTACAATAA---------------------------------------------
''')

tree.workdir = '/Users/alenakizenko/Documents/PhD/hydra_vulgaris_chrom/paml_rt1'


tree.run_model('fb.example')

my_first_fb_model = tree.get_evol_model('fb.example')

print(my_first_fb_model)
